### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by dotmobo** [PaulHendi/ELROND-LKMEX-AIRDROP#1]
Hi, is it possbile to have a requirements.txt file (pip install - r requirements.txt ) to have the right version of libs to install (pandas, erdpy ....)
Thanks !

**Comment by PaulHendi** [comment]
Hey :)
I've added the requirements file, thank you for raising this issue :)
However, you might still need to install additional libraries for erdpy (ncurses) and you'll maybe want to install erdpy with erdpy-up, as opposed to pip.
You'll find more info [here](https://docs.elrond.com/sdk-and-tools/erdpy/installing-erdpy/) :)
